var XNAT_IMAGE_VIEWER_DEMO_SCANS = [{'category': 'dicom',
  'files': ['./sample-data/scans/IMA_Complex_Original/000001.IMA',
            './sample-data/scans/IMA_Complex_Original/000002.IMA',
            './sample-data/scans/IMA_Complex_Original/000003.IMA',
            './sample-data/scans/IMA_Complex_Original/000004.IMA',
            './sample-data/scans/IMA_Complex_Original/000005.IMA',
            './sample-data/scans/IMA_Complex_Original/000006.IMA',
            './sample-data/scans/IMA_Complex_Original/000007.IMA',
            './sample-data/scans/IMA_Complex_Original/000008.IMA',
            './sample-data/scans/IMA_Complex_Original/000009.IMA',
            './sample-data/scans/IMA_Complex_Original/000010.IMA',
            './sample-data/scans/IMA_Complex_Original/000011.IMA',
            './sample-data/scans/IMA_Complex_Original/000012.IMA',
            './sample-data/scans/IMA_Complex_Original/000013.IMA',
            './sample-data/scans/IMA_Complex_Original/000014.IMA',
            './sample-data/scans/IMA_Complex_Original/000015.IMA',
            './sample-data/scans/IMA_Complex_Original/000016.IMA',
            './sample-data/scans/IMA_Complex_Original/000017.IMA',
            './sample-data/scans/IMA_Complex_Original/000018.IMA',
            './sample-data/scans/IMA_Complex_Original/000019.IMA',
            './sample-data/scans/IMA_Complex_Original/000020.IMA',
            './sample-data/scans/IMA_Complex_Original/000021.IMA',
            './sample-data/scans/IMA_Complex_Original/000022.IMA',
            './sample-data/scans/IMA_Complex_Original/000023.IMA',
            './sample-data/scans/IMA_Complex_Original/000024.IMA'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['DICOM']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan',
                           'value': ['IMA_Complex_Original']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['MPRAGE']}},
  'thumbnailUrl': ''},
 {'category': 'dicom',
  'files': ['./sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201002174_1.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201005721_2.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201009393_3.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201013144_4.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201016941_5.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201020863_6.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201024597_7.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201028801_8.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201032739_9.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201036676_10.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201040536_11.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201044114_12.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201047849_13.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201051599_14.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201055271_15.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201059100_16.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201103053_17.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201107053_18.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201111022_19.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201115007_20.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201119085_21.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201123039_22.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201126961_23.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201130883_24.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201135086_25.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201138962_26.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201142962_27.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201146712_28.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201150400_29.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201154134_30.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201157978_31.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201201838_32.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201205651_33.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201209464_34.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201213401_35.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201217620_36.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201221605_37.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201225480_38.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201229324_39.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201233215_40.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201237043_41.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201240919_42.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201244888_43.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201248654_44.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201252232_45.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201255904_46.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201259842_47.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201303748_48.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201307624_49.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201311499_50.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201315218_51.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201318843_52.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201322562_53.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201326500_54.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201330750_55.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201335125_56.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201339110_57.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201343001_58.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201346782_59.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201350939_60.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201354877_61.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201358658_62.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201402361_63.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201406487_64.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201410378_65.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201414190_66.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201417925_67.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201421910_68.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201426019_69.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201430566_70.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201434660_71.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201438770_72.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201442551_73.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201446192_74.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201449974_75.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201453802_76.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201457443_77.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201501131_78.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201504834_79.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201508788_80.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201512632_81.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201517054_82.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201521085_83.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201524851_84.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201528804_85.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201532773_86.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201537024_87.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201541040_88.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201544884_89.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201548774_90.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201552915_91.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201557025_92.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201601275_93.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201605385_94.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201609213_95.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201613010_96.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201617167_97.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201621183_98.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201625183_99.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201629043_100.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201633152_101.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201637371_102.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201641840_103.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201645794_104.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201649903_105.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201653747_106.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201657466_107.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201701467_108.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201705186_109.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201708920_110.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201713139_111.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201717077_112.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201721796_113.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201726015_114.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201730468_115.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201734797_116.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201739000_117.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201743110_118.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201746704_119.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201750392_120.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201754064_121.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201757548_122.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201801314_123.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201805018_124.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201808627_125.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201812502_126.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201816612_127.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201820503_128.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201825066_129.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201829410_130.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201834082_131.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201838535_132.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201842442_133.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201846255_134.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201849958_135.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201853646_136.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201857208_137.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201900990_138.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201904646_139.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201908537_140.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201912397_141.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201916741_142.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201920679_143.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201925226_144.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201929304_145.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201933461_146.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201937680_147.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201941977_148.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201946258_149.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201950665_150.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201954446_151.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710201958212_152.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202002072_153.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202005744_154.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202009572_155.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202013698_156.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202017682_157.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202021870_158.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202025636_159.dcm',
            './sample-data/scans/MR-Brain-2/ICBM_UCLA_1193_MR_SAG_MPRAGE_8_CHANNEL_br_raw_20060710202030011_160.dcm'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['DICOM']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan', 'value': ['MR-Brain-2']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['MPRAGE']}},
  'thumbnailUrl': './sample-data/scans/MR-Brain-2/MR-Brain-2-Thumbnail.jpg'},
 {'category': 'dicom',
  'files': ['./sample-data/scans/IMA_Complex_NII_Converted/case01_20050111_MR1_001_SAG_LOCALIZER_1.nii',
            './sample-data/scans/IMA_Complex_NII_Converted/case01_20050111_MR1_001_SAG_LOCALIZER_2.nii',
            './sample-data/scans/IMA_Complex_NII_Converted/case01_20050111_MR1_001_SAG_LOCALIZER_3.nii',
            './sample-data/scans/IMA_Complex_NII_Converted/case01_20050111_MR1_001_SAG_LOCALIZER_4.nii'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['NifTI']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan',
                           'value': ['IMA_Complex_NII_Converted']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['MPRAGE']}},
  'thumbnailUrl': ''},
 {'category': 'dicom',
  'files': ['./sample-data/scans/IMA_Simple_NII_Converted/case27_20060703_MR1_007_3D_SPGR_VOLUME.nii'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['NifTI']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan',
                           'value': ['IMA_Simple_NII_Converted']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['MPRAGE']}},
  'thumbnailUrl': ''},
 {'category': 'dicom',
  'files': ['./sample-data/scans/IMA_Simple_Original/000001.IMA',
            './sample-data/scans/IMA_Simple_Original/000002.IMA',
            './sample-data/scans/IMA_Simple_Original/000003.IMA',
            './sample-data/scans/IMA_Simple_Original/000004.IMA',
            './sample-data/scans/IMA_Simple_Original/000005.IMA',
            './sample-data/scans/IMA_Simple_Original/000006.IMA',
            './sample-data/scans/IMA_Simple_Original/000007.IMA',
            './sample-data/scans/IMA_Simple_Original/000008.IMA',
            './sample-data/scans/IMA_Simple_Original/000009.IMA',
            './sample-data/scans/IMA_Simple_Original/000010.IMA',
            './sample-data/scans/IMA_Simple_Original/000011.IMA',
            './sample-data/scans/IMA_Simple_Original/000012.IMA',
            './sample-data/scans/IMA_Simple_Original/000013.IMA',
            './sample-data/scans/IMA_Simple_Original/000014.IMA',
            './sample-data/scans/IMA_Simple_Original/000015.IMA',
            './sample-data/scans/IMA_Simple_Original/000016.IMA',
            './sample-data/scans/IMA_Simple_Original/000017.IMA',
            './sample-data/scans/IMA_Simple_Original/000018.IMA',
            './sample-data/scans/IMA_Simple_Original/000019.IMA',
            './sample-data/scans/IMA_Simple_Original/000020.IMA',
            './sample-data/scans/IMA_Simple_Original/000021.IMA',
            './sample-data/scans/IMA_Simple_Original/000022.IMA',
            './sample-data/scans/IMA_Simple_Original/000023.IMA',
            './sample-data/scans/IMA_Simple_Original/000024.IMA',
            './sample-data/scans/IMA_Simple_Original/000025.IMA',
            './sample-data/scans/IMA_Simple_Original/000026.IMA',
            './sample-data/scans/IMA_Simple_Original/000027.IMA',
            './sample-data/scans/IMA_Simple_Original/000028.IMA',
            './sample-data/scans/IMA_Simple_Original/000029.IMA',
            './sample-data/scans/IMA_Simple_Original/000030.IMA',
            './sample-data/scans/IMA_Simple_Original/000031.IMA',
            './sample-data/scans/IMA_Simple_Original/000032.IMA',
            './sample-data/scans/IMA_Simple_Original/000033.IMA',
            './sample-data/scans/IMA_Simple_Original/000034.IMA',
            './sample-data/scans/IMA_Simple_Original/000035.IMA',
            './sample-data/scans/IMA_Simple_Original/000036.IMA',
            './sample-data/scans/IMA_Simple_Original/000037.IMA',
            './sample-data/scans/IMA_Simple_Original/000038.IMA',
            './sample-data/scans/IMA_Simple_Original/000039.IMA',
            './sample-data/scans/IMA_Simple_Original/000040.IMA',
            './sample-data/scans/IMA_Simple_Original/000041.IMA',
            './sample-data/scans/IMA_Simple_Original/000042.IMA',
            './sample-data/scans/IMA_Simple_Original/000043.IMA',
            './sample-data/scans/IMA_Simple_Original/000044.IMA',
            './sample-data/scans/IMA_Simple_Original/000045.IMA',
            './sample-data/scans/IMA_Simple_Original/000046.IMA',
            './sample-data/scans/IMA_Simple_Original/000047.IMA',
            './sample-data/scans/IMA_Simple_Original/000048.IMA',
            './sample-data/scans/IMA_Simple_Original/000049.IMA',
            './sample-data/scans/IMA_Simple_Original/000050.IMA',
            './sample-data/scans/IMA_Simple_Original/000051.IMA',
            './sample-data/scans/IMA_Simple_Original/000052.IMA',
            './sample-data/scans/IMA_Simple_Original/000053.IMA',
            './sample-data/scans/IMA_Simple_Original/000054.IMA',
            './sample-data/scans/IMA_Simple_Original/000055.IMA',
            './sample-data/scans/IMA_Simple_Original/000056.IMA',
            './sample-data/scans/IMA_Simple_Original/000057.IMA',
            './sample-data/scans/IMA_Simple_Original/000058.IMA',
            './sample-data/scans/IMA_Simple_Original/000059.IMA',
            './sample-data/scans/IMA_Simple_Original/000060.IMA'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['DICOM']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan',
                           'value': ['IMA_Simple_Original']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['MPRAGE']}},
  'thumbnailUrl': ''}]

var XNAT_IMAGE_VIEWER_DEMO_SLICER = [{'Name': '5',
  'Size': '',
  'URI': './Slicer/5.mrb',
  'cat_ID': '',
  'category': 'Slicer',
  'collection': 'Slicer',
  'file_content': '',
  'file_format': '',
  'file_tags': '',
  'files': ['./sample-data/Slicer/5/2012-09-30-HN-Atlas-preliminary.mrml',
            './sample-data/Slicer/5/Slicer Data Bundle Scene View_1.png',
            './sample-data/Slicer/5/__MACOSX/._2012-09-30-HN-Atlas-preliminary.mrml',
            './sample-data/Slicer/5/__MACOSX/._Data',
            './sample-data/Slicer/5/__MACOSX/._Slicer Data Bundle Scene View_1.png',
            './sample-data/Slicer/5/__MACOSX/Data/._Arch of Aorta.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Atlas.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Axis.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Brachiocephalic Trunk.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Cervical 3.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Cervical 4.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Cervical 5.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Cervical 6.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Cervical 7.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._HeadAndNeckAtlas-training-colors.txt',
            './sample-data/Slicer/5/__MACOSX/Data/._HN-Atlas.nrrd',
            './sample-data/Slicer/5/__MACOSX/Data/._Hyoid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Clavicle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Common Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left External Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Internal Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Internal Jugular Vein.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Levator Scapulae Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Masseter Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Parotid Gland.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Rib 1.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Rib 2.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Rib 3.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Rib 4.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Rib 5.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Scalenius Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Sternocleidomastoideus Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Subclavian Artery.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Subclavian Vein.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Temporalis Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Trapezius Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Vertebral Artery.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Left Zygomatic Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Mandible.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Master Scene View.png',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_101_right_common_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_102_left_common_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_103_right_subclavian_artery.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_104_left_subclavian_artery.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_105_right_vertebral_artery.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_106_left_vertebral_artery.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_107_right_internal_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_108_left_internal_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_109_right_internal_jugular_vein.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_10_skull.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_110_left_internal_jugular_vein.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_111_right_external_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_112_left_external_carotid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_113_right_subclavian_vein.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_114_left_subclavian_vein.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_115_arch_of_aorta.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_116_brachiocephalic_trunk.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_117_superior_vena_cava.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_11_atlas.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_12_axis.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_13_cervical3.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_14_cervical4.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_15_cervical5.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_16_cervical6.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_17_cervical7.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_21_thoracic1.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_22_thoracic2.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_23_thoracic3.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_24_thoracic4.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_25_mandible.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_26_right_clavicle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_27_left_clavicle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_28_sternum.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_31_rib1.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_32_rib2.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_33_rib3.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_34_rib4.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_35_rib5.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_36_thoracic5.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_49_left_parotid_gland.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_50_right_parotid_gland.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_51_left_temporalis_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_52_right_temporalis_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_53_left_trapezius_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_54_right_trapezius_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_55_left_masseter_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_56_right_masseter_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_57_left_levator_scapulae_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_58_right_levator_scapulae_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_59_left_scalenius_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_60_right_scalenius_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_61_left_sternocleidomastoideus_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_62_right_sternocleidomastoideus_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_63_left_zygomatic_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_64_right_zygomatic_muscle.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Model_9_hyoid.vtk',
            './sample-data/Slicer/5/__MACOSX/Data/._Osirix-Manix-255-res.nrrd',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Clavicle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Common Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right External Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Internal Carotid.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Internal Jugular Vein.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Levator Scapulae Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Masseter Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Parotid Gland.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Rib 1.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Rib 2.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Rib 3.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Rib 4.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Rib 5.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Scalenius Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Sternocleidomastoideus Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Subclavian Artery.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Subclavian Vein.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Temporalis Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Trapezius Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Vertebral Artery.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Right Zygomatic Muscle.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Skull.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Slicer Data Bundle Scene View.png',
            './sample-data/Slicer/5/__MACOSX/Data/._Sternum.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Superior Vena Cava.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Thoracic 1.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Thoracic 2.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Thoracic 3.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Thoracic 4.acsv',
            './sample-data/Slicer/5/__MACOSX/Data/._Thoracic 5.acsv',
            './sample-data/Slicer/5/Data/Arch of Aorta.acsv',
            './sample-data/Slicer/5/Data/Atlas.acsv',
            './sample-data/Slicer/5/Data/Axis.acsv',
            './sample-data/Slicer/5/Data/Brachiocephalic Trunk.acsv',
            './sample-data/Slicer/5/Data/Cervical 3.acsv',
            './sample-data/Slicer/5/Data/Cervical 4.acsv',
            './sample-data/Slicer/5/Data/Cervical 5.acsv',
            './sample-data/Slicer/5/Data/Cervical 6.acsv',
            './sample-data/Slicer/5/Data/Cervical 7.acsv',
            './sample-data/Slicer/5/Data/HeadAndNeckAtlas-training-colors.txt',
            './sample-data/Slicer/5/Data/HN-Atlas.nrrd',
            './sample-data/Slicer/5/Data/Hyoid.acsv',
            './sample-data/Slicer/5/Data/Left Clavicle.acsv',
            './sample-data/Slicer/5/Data/Left Common Carotid.acsv',
            './sample-data/Slicer/5/Data/Left External Carotid.acsv',
            './sample-data/Slicer/5/Data/Left Internal Carotid.acsv',
            './sample-data/Slicer/5/Data/Left Internal Jugular Vein.acsv',
            './sample-data/Slicer/5/Data/Left Levator Scapulae Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Masseter Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Parotid Gland.acsv',
            './sample-data/Slicer/5/Data/Left Rib 1.acsv',
            './sample-data/Slicer/5/Data/Left Rib 2.acsv',
            './sample-data/Slicer/5/Data/Left Rib 3.acsv',
            './sample-data/Slicer/5/Data/Left Rib 4.acsv',
            './sample-data/Slicer/5/Data/Left Rib 5.acsv',
            './sample-data/Slicer/5/Data/Left Scalenius Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Sternocleidomastoideus Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Subclavian Artery.acsv',
            './sample-data/Slicer/5/Data/Left Subclavian Vein.acsv',
            './sample-data/Slicer/5/Data/Left Temporalis Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Trapezius Muscle.acsv',
            './sample-data/Slicer/5/Data/Left Vertebral Artery.acsv',
            './sample-data/Slicer/5/Data/Left Zygomatic Muscle.acsv',
            './sample-data/Slicer/5/Data/Mandible.acsv',
            './sample-data/Slicer/5/Data/Master Scene View.png',
            './sample-data/Slicer/5/Data/Model_101_right_common_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_102_left_common_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_103_right_subclavian_artery.vtk',
            './sample-data/Slicer/5/Data/Model_104_left_subclavian_artery.vtk',
            './sample-data/Slicer/5/Data/Model_105_right_vertebral_artery.vtk',
            './sample-data/Slicer/5/Data/Model_106_left_vertebral_artery.vtk',
            './sample-data/Slicer/5/Data/Model_107_right_internal_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_108_left_internal_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_109_right_internal_jugular_vein.vtk',
            './sample-data/Slicer/5/Data/Model_10_skull.vtk',
            './sample-data/Slicer/5/Data/Model_110_left_internal_jugular_vein.vtk',
            './sample-data/Slicer/5/Data/Model_111_right_external_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_112_left_external_carotid.vtk',
            './sample-data/Slicer/5/Data/Model_113_right_subclavian_vein.vtk',
            './sample-data/Slicer/5/Data/Model_114_left_subclavian_vein.vtk',
            './sample-data/Slicer/5/Data/Model_115_arch_of_aorta.vtk',
            './sample-data/Slicer/5/Data/Model_116_brachiocephalic_trunk.vtk',
            './sample-data/Slicer/5/Data/Model_117_superior_vena_cava.vtk',
            './sample-data/Slicer/5/Data/Model_11_atlas.vtk',
            './sample-data/Slicer/5/Data/Model_12_axis.vtk',
            './sample-data/Slicer/5/Data/Model_13_cervical3.vtk',
            './sample-data/Slicer/5/Data/Model_14_cervical4.vtk',
            './sample-data/Slicer/5/Data/Model_15_cervical5.vtk',
            './sample-data/Slicer/5/Data/Model_16_cervical6.vtk',
            './sample-data/Slicer/5/Data/Model_17_cervical7.vtk',
            './sample-data/Slicer/5/Data/Model_21_thoracic1.vtk',
            './sample-data/Slicer/5/Data/Model_22_thoracic2.vtk',
            './sample-data/Slicer/5/Data/Model_23_thoracic3.vtk',
            './sample-data/Slicer/5/Data/Model_24_thoracic4.vtk',
            './sample-data/Slicer/5/Data/Model_25_mandible.vtk',
            './sample-data/Slicer/5/Data/Model_26_right_clavicle.vtk',
            './sample-data/Slicer/5/Data/Model_27_left_clavicle.vtk',
            './sample-data/Slicer/5/Data/Model_28_sternum.vtk',
            './sample-data/Slicer/5/Data/Model_31_rib1.vtk',
            './sample-data/Slicer/5/Data/Model_32_rib2.vtk',
            './sample-data/Slicer/5/Data/Model_33_rib3.vtk',
            './sample-data/Slicer/5/Data/Model_34_rib4.vtk',
            './sample-data/Slicer/5/Data/Model_35_rib5.vtk',
            './sample-data/Slicer/5/Data/Model_36_thoracic5.vtk',
            './sample-data/Slicer/5/Data/Model_49_left_parotid_gland.vtk',
            './sample-data/Slicer/5/Data/Model_50_right_parotid_gland.vtk',
            './sample-data/Slicer/5/Data/Model_51_left_temporalis_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_52_right_temporalis_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_53_left_trapezius_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_54_right_trapezius_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_55_left_masseter_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_56_right_masseter_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_57_left_levator_scapulae_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_58_right_levator_scapulae_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_59_left_scalenius_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_60_right_scalenius_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_61_left_sternocleidomastoideus_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_62_right_sternocleidomastoideus_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_63_left_zygomatic_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_64_right_zygomatic_muscle.vtk',
            './sample-data/Slicer/5/Data/Model_9_hyoid.vtk',
            './sample-data/Slicer/5/Data/Osirix-Manix-255-res.nrrd',
            './sample-data/Slicer/5/Data/Right Clavicle.acsv',
            './sample-data/Slicer/5/Data/Right Common Carotid.acsv',
            './sample-data/Slicer/5/Data/Right External Carotid.acsv',
            './sample-data/Slicer/5/Data/Right Internal Carotid.acsv',
            './sample-data/Slicer/5/Data/Right Internal Jugular Vein.acsv',
            './sample-data/Slicer/5/Data/Right Levator Scapulae Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Masseter Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Parotid Gland.acsv',
            './sample-data/Slicer/5/Data/Right Rib 1.acsv',
            './sample-data/Slicer/5/Data/Right Rib 2.acsv',
            './sample-data/Slicer/5/Data/Right Rib 3.acsv',
            './sample-data/Slicer/5/Data/Right Rib 4.acsv',
            './sample-data/Slicer/5/Data/Right Rib 5.acsv',
            './sample-data/Slicer/5/Data/Right Scalenius Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Sternocleidomastoideus Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Subclavian Artery.acsv',
            './sample-data/Slicer/5/Data/Right Subclavian Vein.acsv',
            './sample-data/Slicer/5/Data/Right Temporalis Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Trapezius Muscle.acsv',
            './sample-data/Slicer/5/Data/Right Vertebral Artery.acsv',
            './sample-data/Slicer/5/Data/Right Zygomatic Muscle.acsv',
            './sample-data/Slicer/5/Data/Skull.acsv',
            './sample-data/Slicer/5/Data/Slicer Data Bundle Scene View.png',
            './sample-data/Slicer/5/Data/Sternum.acsv',
            './sample-data/Slicer/5/Data/Superior Vena Cava.acsv',
            './sample-data/Slicer/5/Data/Thoracic 1.acsv',
            './sample-data/Slicer/5/Data/Thoracic 2.acsv',
            './sample-data/Slicer/5/Data/Thoracic 3.acsv',
            './sample-data/Slicer/5/Data/Thoracic 4.acsv',
            './sample-data/Slicer/5/Data/Thoracic 5.acsv'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan', 'value': ['']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['']}},
  'thumbnailUrl': './sample-data/Slicer/5/Slicer Data Bundle Scene View_1.png'},
 {'Name': '4',
  'Size': '',
  'URI': './Slicer/4.mrb',
  'cat_ID': '',
  'category': 'Slicer',
  'collection': 'Slicer',
  'file_content': '',
  'file_format': '',
  'file_tags': '',
  'files': ['./sample-data/Slicer/4/.DS_Store',
            './sample-data/Slicer/4/2012-09-17-VR-test.mrml',
            './sample-data/Slicer/4/Slicer Data Bundle Scene View.png',
            './sample-data/Slicer/4/__MACOSX/._2012-09-17-VR-test.mrml',
            './sample-data/Slicer/4/__MACOSX/._Data',
            './sample-data/Slicer/4/__MACOSX/._Slicer Data Bundle Scene View.png',
            './sample-data/Slicer/4/__MACOSX/Data/._AnnotationROI.acsv',
            './sample-data/Slicer/4/__MACOSX/Data/._CT-Chest-Contrast-Enhanced.vp',
            './sample-data/Slicer/4/__MACOSX/Data/._CTA-cardio.nrrd',
            './sample-data/Slicer/4/__MACOSX/Data/._Master Scene View.png',
            './sample-data/Slicer/4/__MACOSX/Data/._View1.png',
            './sample-data/Slicer/4/__MACOSX/Data/._View2.png',
            './sample-data/Slicer/4/__MACOSX/Data/._View3.png',
            './sample-data/Slicer/4/__MACOSX/Data/._view4.png',
            './sample-data/Slicer/4/__MACOSX/Data/._VolumeProperty.vp',
            './sample-data/Slicer/4/Data/AnnotationROI.acsv',
            './sample-data/Slicer/4/Data/CT-Chest-Contrast-Enhanced.vp',
            './sample-data/Slicer/4/Data/CTA-cardio.nrrd',
            './sample-data/Slicer/4/Data/Master Scene View.png',
            './sample-data/Slicer/4/Data/View1.png',
            './sample-data/Slicer/4/Data/View2.png',
            './sample-data/Slicer/4/Data/View3.png',
            './sample-data/Slicer/4/Data/view4.png',
            './sample-data/Slicer/4/Data/VolumeProperty.vp'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan', 'value': ['']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['']}},
  'thumbnailUrl': './sample-data/Slicer/4/Slicer Data Bundle Scene View.png'},
 {'Name': '7',
  'Size': '',
  'URI': './Slicer/7.mrb',
  'cat_ID': '',
  'category': 'Slicer',
  'collection': 'Slicer',
  'file_content': '',
  'file_format': '',
  'file_tags': '',
  'files': ['./sample-data/Slicer/7/.DS_Store',
            './sample-data/Slicer/7/2013-02-14-Final.mrml',
            './sample-data/Slicer/7/2013-02-14-Final_HandMotorArea.mrml',
            './sample-data/Slicer/7/2013-02-14-Final_PeritumoralFibers.mrml',
            './sample-data/Slicer/7/2013-02-14-Final_VirtualProbing.mrml',
            './sample-data/Slicer/7/Slicer Data Bundle Scene View_4.png',
            './sample-data/Slicer/7/__MACOSX/._2013-02-14-Final.mrml',
            './sample-data/Slicer/7/__MACOSX/._2013-02-14-Final_HandMotorArea.mrml',
            './sample-data/Slicer/7/__MACOSX/._2013-02-14-Final_PeritumoralFibers.mrml',
            './sample-data/Slicer/7/__MACOSX/._2013-02-14-Final_VirtualProbing.mrml',
            './sample-data/Slicer/7/__MACOSX/._Data',
            './sample-data/Slicer/7/__MACOSX/._Slicer Data Bundle Scene View_4.png',
            './sample-data/Slicer/7/__MACOSX/Data/._B-splineDeformedSPGR.nrrd',
            './sample-data/Slicer/7/__MACOSX/Data/._Broca.acsv',
            './sample-data/Slicer/7/__MACOSX/Data/._CorticoSpinalTract.acsv',
            './sample-data/Slicer/7/__MACOSX/Data/._DiffusionEditorBaselineNode.nrrd',
            './sample-data/Slicer/7/__MACOSX/Data/._DiffusionEditorTensorNode.nrrd',
            './sample-data/Slicer/7/__MACOSX/Data/._DiffusionTensorDisplayProperties.ctbl',
            './sample-data/Slicer/7/__MACOSX/Data/._DiffusionTensorDisplayProperties_1.ctbl',
            './sample-data/Slicer/7/__MACOSX/Data/._DiffusionTensorDisplayProperties_2.ctbl',
            './sample-data/Slicer/7/__MACOSX/Data/._DilatedTumor.nrrd',
            './sample-data/Slicer/7/__MACOSX/Data/._Handmotor Area.png',
            './sample-data/Slicer/7/__MACOSX/Data/._HandMotorArea.acsv',
            './sample-data/Slicer/7/__MACOSX/Data/._LabelmapSeedingModel.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._LabelmapSeedingModel.vtk',
            './sample-data/Slicer/7/__MACOSX/Data/._Overview.png',
            './sample-data/Slicer/7/__MACOSX/Data/._Peritumoral Fibers.png',
            './sample-data/Slicer/7/__MACOSX/Data/._Skin.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._Skin.vtk',
            './sample-data/Slicer/7/__MACOSX/Data/._Tumor.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._Tumor.vtk',
            './sample-data/Slicer/7/__MACOSX/Data/._Ventricles.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._Ventricles.vtk',
            './sample-data/Slicer/7/__MACOSX/Data/._Virtual Probe.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._VirtualProbing.png',
            './sample-data/Slicer/7/__MACOSX/Data/._WhiteMatter.stl',
            './sample-data/Slicer/7/__MACOSX/Data/._WhiteMatter.vtk',
            './sample-data/Slicer/7/Data/B-splineDeformedSPGR.nrrd',
            './sample-data/Slicer/7/Data/Broca.acsv',
            './sample-data/Slicer/7/Data/CorticoSpinalTract.acsv',
            './sample-data/Slicer/7/Data/DiffusionEditorBaselineNode.nrrd',
            './sample-data/Slicer/7/Data/DiffusionEditorTensorNode.nrrd',
            './sample-data/Slicer/7/Data/DiffusionTensorDisplayProperties.ctbl',
            './sample-data/Slicer/7/Data/DiffusionTensorDisplayProperties_1.ctbl',
            './sample-data/Slicer/7/Data/DiffusionTensorDisplayProperties_2.ctbl',
            './sample-data/Slicer/7/Data/DilatedTumor.nrrd',
            './sample-data/Slicer/7/Data/Handmotor Area.png',
            './sample-data/Slicer/7/Data/HandMotorArea.acsv',
            './sample-data/Slicer/7/Data/LabelmapSeedingModel.stl',
            './sample-data/Slicer/7/Data/LabelmapSeedingModel.vtk',
            './sample-data/Slicer/7/Data/Overview.png',
            './sample-data/Slicer/7/Data/Peritumoral Fibers.png',
            './sample-data/Slicer/7/Data/Skin.stl',
            './sample-data/Slicer/7/Data/Skin.vtk',
            './sample-data/Slicer/7/Data/Tumor.stl',
            './sample-data/Slicer/7/Data/Tumor.vtk',
            './sample-data/Slicer/7/Data/Ventricles.stl',
            './sample-data/Slicer/7/Data/Ventricles.vtk',
            './sample-data/Slicer/7/Data/Virtual Probe.stl',
            './sample-data/Slicer/7/Data/VirtualProbing.png',
            './sample-data/Slicer/7/Data/WhiteMatter.stl',
            './sample-data/Slicer/7/Data/WhiteMatter.vtk'],
  'sessionInfo': {'Accession #': {'label': 'Acession #', 'value': []},
                  'AcqDate': {'label': 'Acq. Date', 'value': []},
                  'Age': {'label': 'Age', 'value': ['-100']},
                  'Format': {'label': 'Format', 'value': ['']},
                  'Gender': {'label': 'Gender', 'value': ['de-identified']},
                  'Handedness': {'label': 'Handedness', 'value': ['none']},
                  'Scan': {'label': 'Scan', 'value': ['']},
                  'Scanner': {'label': 'Scanner', 'value': ['']},
                  'SessionID': {'label': 'Session ID',
                                'value': ['XNATImageViewerDemo']},
                  'experiments': 'XNATImageViewerDemo',
                  'prepend': '',
                  'projects': 'XNATImageViewerDemo',
                  'subjects': 'XNATImageViewerDemo',
                  'type': {'label': 'type', 'value': ['']}},
  'thumbnailUrl': './sample-data/Slicer/7/Slicer Data Bundle Scene View_4.png'}]