// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../gxnat/Path.js', ['gxnat.Path'], ['goog.Disposable', 'goog.object', 'gxnat']);
goog.addDependency('../../../gxnat/ProjectTree.js', ['gxnat.ProjectTree'], ['goog.Disposable', 'goog.array', 'goog.object', 'goog.string', 'gxnat', 'gxnat.Path']);
goog.addDependency('../../../gxnat/Zip.js', ['gxnat.Zip'], ['JSZip', 'goog.Disposable', 'goog.object', 'gxnat']);
goog.addDependency('../../../gxnat/gxnat.js', ['gxnat'], ['goog.array', 'goog.net.XhrIo', 'goog.object', 'goog.string']);
goog.addDependency('../../../gxnat/slicerNode/Annotations.js', ['gxnat.slicerNode.Annotations'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/BackgroundColor.js', ['gxnat.slicerNode.BackgroundColor'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Camera.js', ['gxnat.slicerNode.Camera'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Display.js', ['gxnat.slicerNode.Display'], ['gxnat.slicerNode', 'gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Displayable.js', ['gxnat.slicerNode.Displayable'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Layout.js', ['gxnat.slicerNode.Layout'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Mesh.js', ['gxnat.slicerNode.Mesh'], ['gxnat.slicerNode.Display']);
goog.addDependency('../../../gxnat/slicerNode/Mrml.js', ['gxnat.slicerNode.Mrml'], ['gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Node.js', ['gxnat.slicerNode.Node'], ['gxnat.slicerNode']);
goog.addDependency('../../../gxnat/slicerNode/SceneView.js', ['gxnat.slicerNode.SceneView'], ['gxnat.slicerNode.BackgroundColor', 'gxnat.slicerNode.Node']);
goog.addDependency('../../../gxnat/slicerNode/Volume.js', ['gxnat.slicerNode.Volume'], ['goog.array', 'goog.math.Matrix', 'gxnat', 'gxnat.slicerNode', 'gxnat.slicerNode.Display']);
goog.addDependency('../../../gxnat/slicerNode/slicerNode.js', ['gxnat.slicerNode'], []);
goog.addDependency('../../../gxnat/slicerUtils.js', ['gxnat.slicerUtils'], ['goog.array', 'goog.dom', 'goog.dom.DomHelper', 'goog.dom.xml', 'goog.string', 'goog.string.path', 'gxnat', 'gxnat.slicerNode', 'gxnat.slicerNode.Annotations', 'gxnat.slicerNode.BackgroundColor', 'gxnat.slicerNode.Camera', 'gxnat.slicerNode.Display', 'gxnat.slicerNode.Displayable', 'gxnat.slicerNode.Layout', 'gxnat.slicerNode.Mesh', 'gxnat.slicerNode.Mrml', 'gxnat.slicerNode.Node', 'gxnat.slicerNode.SceneView', 'gxnat.slicerNode.Volume']);
goog.addDependency('../../../gxnat/vis/AjaxViewableTree.js', ['gxnat.vis.AjaxViewableTree'], ['goog.array', 'goog.object', 'goog.string', 'gxnat', 'gxnat.Path', 'gxnat.vis.ViewableTree']);
goog.addDependency('../../../gxnat/vis/RenderProperties.js', ['gxnat.vis.RenderProperties'], ['goog.Disposable', 'goog.object', 'gxnat.slicerNode.Mesh', 'gxnat.slicerNode.Node', 'gxnat.slicerNode.SceneView', 'gxnat.slicerNode.Volume']);
goog.addDependency('../../../gxnat/vis/Renderable.js', ['gxnat.vis.Renderable'], ['gxnat.slicerNode.Node', 'gxnat.vis.RenderProperties', 'gxnat.vis.VisNode']);
goog.addDependency('../../../gxnat/vis/Scan.js', ['gxnat.vis.Scan'], ['goog.object', 'goog.string', 'gxnat', 'gxnat.Path', 'gxnat.vis.AjaxViewableTree', 'gxnat.vis.Viewable', 'gxnat.vis.ViewableGroup']);
goog.addDependency('../../../gxnat/vis/Slicer.js', ['gxnat.vis.Slicer'], ['goog.array', 'goog.string', 'goog.string.path', 'gxnat', 'gxnat.slicerNode.Displayable', 'gxnat.slicerNode.Mrml', 'gxnat.slicerNode.SceneView', 'gxnat.slicerNode.Volume', 'gxnat.slicerUtils', 'gxnat.vis.AjaxViewableTree', 'gxnat.vis.Scan', 'gxnat.vis.Viewable', 'gxnat.vis.ViewableGroup', 'nrg.string']);
goog.addDependency('../../../gxnat/vis/Viewable.js', ['gxnat.vis.Viewable'], ['goog.array', 'goog.object', 'goog.string', 'gxnat.Zip', 'gxnat.slicerNode.Node', 'gxnat.vis.Renderable']);
goog.addDependency('../../../gxnat/vis/ViewableGroup.js', ['gxnat.vis.ViewableGroup'], ['goog.array', 'gxnat.vis.Renderable', 'gxnat.vis.Viewable']);
goog.addDependency('../../../gxnat/vis/ViewableTree.js', ['gxnat.vis.ViewableTree'], ['goog.array', 'goog.object', 'gxnat.vis.ViewableGroup', 'gxnat.vis.VisNode']);
goog.addDependency('../../../gxnat/vis/VisNode.js', ['gxnat.vis.VisNode'], ['goog.Disposable']);
goog.addDependency('../../../gxnat/vis/vis.js', ['gxnat.vis'], []);
